### ISSUE TITLE
choosing basis for solvers

### ISSUE THREAD

**Issue by saynbabul** [eltrompetero/coniii#25]
Hello, I know the default basis for the ising model in this package is {-1,1}, but is it possible to select a different basis {0,1} when running the solvers?

**Comment by eltrompetero** [comment]
It's not generally possible to run the solvers with a different basis because the spin values are hard-coded in them. I believe the only exception to this is the exact solution, which only relies on minimizing the distance between the vector of correlations. But even for this one, you still have to set the class members manually.

Is there a particular reason you want the {0,1} basis? It yields little to no computational benefits for the implemented algorithms.

In any case, you should be able to convert from the {-1,1} to the {0,1} basis for the fields and couplings and the correlations via algebraic operations. 

I've implemented such a conversion in `utils.py` called `convert_params` and there is even a general one for kth order interactions called `ising_convert_params`. There's another for magnetizations and pair correlations called `convert_corr`.

**Comment by saynbabul** [comment]
I see, thank you so much for your quick reply. Its not really a computational reason, more of just a convention, so I’ll check out the utils.py conversion. 

Thank you,
Shazia

**Comment by eltrompetero** [comment]
Great. Glad that was helpful. Happy to help.

**Comment by saynbabul** [comment]
Hello, 

I had another question if that’s ok. I am trying to use the MCH method to solve an ising system, for a system of size 50. I assumed from the documentation that its only necessary to run enumerate.py to generating the ising equations, if you are using the Enumerate solver. However, when I try to run the MCH method, I get the error “Python file enumerating the Ising equations for system for size must be written”

Thank you so much,
Shazia

**Comment by eltrompetero** [comment]
For organization, I moved this to another issue. Please see the thread there...
