### ISSUE TITLE
calc_observables  — a little more documentation?

### ISSUE THREAD

**Issue by simon-dedeo** [eltrompetero/coniii#32]
Hello genius gurus — 

We're booting up your code to do fun things!

One thing I was hoping to get a little more information on is how to set "calc_observables" to something other than the default.

It would be very helpful (for example!) to see how one might define a different calc_observables function, and pass it to the system to fit. For example, how would I write a function that fixed (for example) a few of the triplet correlations as well?

(In the end, we're planning to use this with some missing data, so we want to redefine calc_observables so that it's matching just the stuff we know — e.g., if we have 500 observations of a 20-spin system, maybe for observation 451 we only have 18 of the spins measured; we want to make sure that the  expectation values are correctly calculated.)

Any help very gratefully received! I have a feeling that this might be useful to others. 

BTW we are planning right now just to use the MPF — but perhaps if we get calc_observables working correctly, it can be slotted in to the MCH as well?

Thank you for any help,

The Pittsburgh Gang

**Comment by eltrompetero** [comment]
Hi, Simon, yes definitely possible. I do this all the time, but for sure it's not well documented. I hope such details will the added in the future, but this is a resource problem...

The short answer is that the details are hiding in utils.define_ising_helper_functions() which provides helper functions that are used elsewhere such as in the MCH algorithm. 

calc_observables() goes into a Solver instance as a method. One also need define the corresponding calc_e() to calculate the energy of each state. This is defined implicitly for the Ising and Triplet interaction cases. See the Model instance that is part of the Solver instance (solver.model). You can see how this is done in Solver.basic_setup(), and an example of accounting for triplets is in the Jupyter notebook usage guide.

Note that the MCH method uses calc_observables() to extract the observables separately for each state and then subsequently takes the average. If one has set spins to 0 to represent unobserved spins, the averaged observables are wrong. I'm sure you're aware that maximizing the likelihood given unobserved spins is a much trickier numerical problem. I've developed software for this, but it is not at the moment part of ConIII.

However! I found that (heuristically) taking averages and ignoring the "zeros" was not horribly wrong in previous work. This is, of course, totally fine if one has the expectation that spins are randomly unobserved and a sufficiently large sample. If this is a heuristic you want to use, you can force the algorithm to fit to your "correct" observables by explicitly setting the "constraints" parameter in Solver.solve(). I believe this is available for MCH.

As a final comment, there are new Solver classes called SparseEnumerate and SparseMCH, which allow one to specify a few parameters instead of all (i.e. fix most coupligns to 0 instead of fitting to all of them).

**Comment by simon-dedeo** [comment]
This makes sense Eddie!

With MPF, it seems like we can actually set values of the observables to NaN, as long as we switch out the .mean(0) calls in your code for .nanmean(0) calls. Is that correct? 

I say that because we were looking at the code together this morning, and it *looks* like all MPF ever does is average the columns of the matrix, and so nanmean will do the average, but don't include cases where the spin was unobserved. In the MCH case, no such luck — it's much harder.

Another option is (as you say!) to use zero (rather than +1, -1). Our feeling here has been that there are actually two separate cases:

1. where the observation was made, but the person ended up being unsure; this is something we flag as zero.
2. where the observation was never made; in this case, labelling as zero "dilutes" the information in the wrong way and NaN seems right.

Imagine (to take your supreme court case) that we have a case and for some reason we didn't record Clarence Thomas' ruling. If we flag it as a zero, this is equivalent to saying that "in this case, it's 50-50 that CT made a liberal ruling, and so that suggests CT is not as conservative" which seems wrong. If we flag it as a NaN, then we're saying "only use the data where we observed CT's ruling to compute his average."

**Comment by eltrompetero** [comment]
With MCH, you can set the constraints keyword parameter when calling MCH.solve(). And there you can calculate the correlations however you like...the "non-observation" is not a problem when sampling from the model.

But yes it's a more subtle issue. In our take, one can calculate a self-consistent equation by marginalizing over unobserved spins. As far as we can tell, this is highly degenerate in some cases, which is in and of itself a very interesting problem.

**Comment by eltrompetero** [comment]
By the way, I just pushed an updated v3.0.1. Some useful updates to the installation procedure and updated readme.
